#!/usr/bin/env python3
"""Create or resume a bilingual Project2Learn workspace."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


STARTER_GUIDE = """# Learning Guide / 学习指南 — Start Here 从这里开始

> First time using this course? Read this page first. It explains every file,
> the reading order, and what to do at each step.
> 第一次使用本课程？先读这一页：它告诉你每个文件是什么、按什么顺序学。

This is a placeholder generated by init_workspace.py. Before marking the course
`ready`, the agent MUST replace it with a course-specific guide following the
contract in references/output-contract.md (artifact_id: getting-started).

## Suggested reading order / 建议阅读顺序

1. `course/<lang>/project-map.md` — purpose, user journey, subsystems
2. `course/<lang>/knowledge-graph.md` — project-required competency dependencies
3. `course/<lang>/readiness.md` — your baseline, gaps, and personalized entry conditions
4. `course/<lang>/foundations/FNN-*.md` — only the prerequisite bridges you need
5. `course/<lang>/project-evolution.md` — why each project stage appears
6. `course/<lang>/roadmap.md` — what to build and in what order
7. `course/<lang>/milestones/NN-*.md` — project reconstruction, one causal stage at a time
8. `course/<lang>/architecture.md` — how mature components cooperate (revisit after milestones)
9. Write exercises and project code under `student/`; submit evidence to the tutor.

Repository: {repository}
"""


def initial_progress(reference: Path, revision: str = "") -> dict:
    return {
        "schema_version": 3,
        "repository": {
            "name": reference.name,
            "source": str(reference),
            "revision": revision,
        },
        "course_status": "analyzing",
        "learning_phase": "assessing",
        "current_unit": {"kind": "assessment", "id": "readiness"},
        "current_milestone": 0,
        "learner_profile": {
            "assessment_mode": "pending",
            "learning_mode": "pending",
            "goals": [],
            "constraints": [],
            "competencies": [],
        },
        "assessment_history": [],
        "practice_evidence": [],
        "foundation_units": [],
        "milestones": [],
        "hint_history": [],
        "open_improvements": [],
        "learner_choices": [],
        "last_review": None,
        "recommended_next_action": "analyze_repository_then_assess_prerequisites",
    }


def _paths_overlap(first: Path, second: Path) -> bool:
    return first == second or first in second.parents or second in first.parents


def initialize_workspace(reference: Path, output_root: Path, revision: str = "") -> Path:
    reference = reference.resolve(strict=True)
    output_root = output_root.resolve()
    if not reference.is_dir():
        raise ValueError("reference must be a directory")
    slug = re.sub(r"[^a-zA-Z0-9._-]+", "-", reference.name).strip("-") or "repository"
    workspace = (output_root / slug).resolve()
    if _paths_overlap(reference, workspace):
        raise ValueError("learning workspace and reference repository must not overlap")

    progress_path = workspace / "progress.json"
    if progress_path.exists():
        try:
            progress = json.loads(progress_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise ValueError(f"existing progress.json is invalid: {error}") from error
        stored_source = progress.get("repository", {}).get("source", "")
        if not stored_source or Path(stored_source).resolve() != reference:
            raise ValueError("existing workspace belongs to a different reference repository")
        stored_revision = progress["repository"].get("revision", "")
        if revision and stored_revision and revision != stored_revision:
            progress["repository"]["previous_revision"] = stored_revision
            progress["repository"]["revision"] = revision
            progress["course_status"] = "analyzing"
            progress["recommended_next_action"] = "reanalyze_repository"
            progress_path.write_text(
                json.dumps(progress, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
            )
        elif revision and not stored_revision:
            progress["repository"]["revision"] = revision
            progress_path.write_text(
                json.dumps(progress, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
            )

    for relative in (
        "course/zh-CN/foundations",
        "course/en/foundations",
        "course/zh-CN/milestones",
        "course/en/milestones",
        "student",
        "reviews/zh-CN",
        "reviews/en",
    ):
        (workspace / relative).mkdir(parents=True, exist_ok=True)

    guide = workspace / "course" / "GETTING_STARTED.md"
    if not guide.exists():
        guide.write_text(
            STARTER_GUIDE.format(repository=reference.name), encoding="utf-8"
        )

    if not progress_path.exists():
        progress_path.write_text(
            json.dumps(initial_progress(reference, revision), ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    return workspace


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Create or resume a separate bilingual Project2Learn workspace."
    )
    parser.add_argument("--reference", required=True, type=Path)
    parser.add_argument("--output-root", required=True, type=Path)
    parser.add_argument("--revision", default="")
    args = parser.parse_args(argv)
    try:
        workspace = initialize_workspace(args.reference, args.output_root, args.revision)
    except (OSError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print(workspace)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
